import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type LangCode = 'eng' | 'ru' | 'uz';

const STORAGE_KEY = 'app_lang';

const translations: Record<LangCode, Record<string, string>> = {
  eng: {
    nav_dashboard: 'Dashboard',
    nav_students: 'Students',
    nav_settings: 'Settings',
    nav_groups: 'Groups',
    nav_schedule: 'Schedule',
    nav_students_teacher: 'Students',
    nav_tasks: 'Tasks',
    nav_profile: 'Profile',
    nav_organizations: 'Organizations',
    nav_admins: 'Admins',
    nav_teachers: 'Teachers',
    nav_teacher_detail: 'Teacher',
    nav_notifications: 'Notifications',
    nav_grading: 'Grading',
    nav_student: 'Student',
    nav_parent: 'Parent',
    nav_support: 'Support',
    logout: 'Logout',
    center_admin: 'Center admin',
    teacher: 'Teacher',
    superadmin: 'Superadmin',
    student_my_homeworks: 'My Homeworks',
    student_greeting_morning: 'Good Morning',
    student_greeting_afternoon: 'Good Afternoon',
    student_greeting_evening: 'Good Evening',
    student_fallback: 'Student',
    student_pending: 'Pending',
    student_submitted: 'Submitted',
    student_graded: 'Graded',
    student_overdue: 'Overdue',
    student_all: 'All',
    student_book_appointment: 'Additional classes',
    student_with_support_teacher: 'With Assistant Teacher',
    student_no_homework: 'No homework found',
    student_teacher_fallback: 'Teacher',
    student_submitted_on: 'Submitted on',
    student_retry: 'Retry',
    nav_home: 'Home',
    nav_ranking: 'Ranking',
    nav_appointments: 'Appointments',
    schedule_my_schedule: 'My Schedule',
    schedule_teacher: 'Teacher:',
    schedule_not_assigned: 'Not assigned',
    schedule_today: 'Today',
    schedule_class: 'class',
    schedule_classes: 'classes',
    schedule_practice_count: 'practice',
    schedule_no_classes: 'No Classes',
    schedule_free_day: 'Enjoy your free day! 🎉',
    schedule_now: 'Now',
    schedule_soon: 'Soon',
    schedule_done: 'Done',
    schedule_in_progress: 'In progress',
    schedule_min_left: 'min left',
    schedule_practice: 'Practice',
    schedule_week_overview: 'Week Overview',
    schedule_retry: 'Retry',
    schedule_contact_teacher: 'Please contact your teacher',
    schedule_mon: 'Mon', schedule_tue: 'Tue', schedule_wed: 'Wed', schedule_thu: 'Thu', schedule_fri: 'Fri', schedule_sat: 'Sat', schedule_sun: 'Sun',
    schedule_monday: 'Monday', schedule_tuesday: 'Tuesday', schedule_wednesday: 'Wednesday', schedule_thursday: 'Thursday', schedule_friday: 'Friday', schedule_saturday: 'Saturday', schedule_sunday: 'Sunday',
    schedule_groups: 'groups',
    schedule_add_practice_lesson: '+ Add Practice Lesson',
    schedule_add_practice_modal_title: 'Add Practice Lesson',
    schedule_add_practice_modal_subtitle: 'Schedule an extra class',
    schedule_group_label: 'Group',
    schedule_select_group: 'Select group',
    schedule_all_groups: 'All Groups',
    schedule_date: 'Date',
    schedule_start_time: 'Start Time',
    schedule_end_time: 'End Time',
    schedule_description_optional: 'Description (optional)',
    schedule_description_placeholder: 'e.g., Exam preparation',
    schedule_saving: 'Saving...',
    schedule_add_practice_btn: 'Add Practice',
    schedule_fetch_error: 'Failed to fetch schedule',
    students_my_students: 'My Students',
    students_count: 'students',
    students_count_parents: 'parents',
    students_tab_students: 'Students',
    students_tab_parents: 'Parents',
    students_search_students: 'Search by name, phone or group...',
    students_search_parents: 'Search by name or phone...',
    students_no_students: 'No students found',
    students_no_parents: 'No parents found',
    students_children: 'Children:',
    students_call: 'Call',
    students_remove_parent: 'Remove parent',
    students_assign_parent: 'Assign parent',
    students_add_student: 'Add student',
    students_add_parent: 'Add parent',
    students_modal_new_student: 'New student',
    students_modal_fio: 'Full name *',
    students_modal_fio_placeholder: 'Student full name',
    students_modal_phone: 'Phone *',
    students_modal_login: 'Login *',
    students_modal_password: 'Password *',
    students_modal_assign_group: 'Assign to group',
    students_modal_select_group: 'Select group',
    students_modal_loading: 'Loading...',
    students_modal_add_student_btn: 'Add student',
    students_modal_create_parent_title: 'Create Parent',
    students_modal_full_name: 'Full Name *',
    students_modal_parent_name_placeholder: 'Parent full name',
    students_modal_creating: 'Creating...',
    students_modal_create_parent_btn: 'Create Parent',
    students_modal_assign_children: 'Assign Children (optional)',
    students_modal_no_group: 'No group',
    students_modal_assign_parent_title: 'Assign Parent',
    students_modal_assign_to: 'Assign parent to',
    students_modal_no_parents_yet: 'No parents created yet',
    students_modal_create_parent_first: 'Create Parent First',
    students_modal_select_parent: 'Select Parent',
    students_modal_select_parent_placeholder: 'Select a parent...',
    students_modal_assigning: 'Assigning...',
    students_modal_assign_btn: 'Assign Parent',
    students_modal_new: 'New',
    students_modal_edit_parent: 'Edit Parent',
    students_modal_new_password: 'New Password',
    students_modal_password_leave_empty: 'Leave empty to keep current',
    students_modal_password_leave_empty_hint: 'Leave empty if you don\'t want to change the password',
    students_modal_assigned_children: 'Assigned Children',
    students_modal_saving: 'Saving...',
    students_modal_save_changes: 'Save Changes',
    students_confirm_delete_parent: 'Delete Parent',
    students_confirm_remove_parent: 'Remove Parent',
    students_confirm_delete_message: 'Are you sure you want to delete {name}? This will also remove the parent from all assigned students.',
    students_confirm_remove_message: 'Are you sure you want to remove parent from {name}?',
    students_confirm_delete_btn: 'Delete',
    students_confirm_remove_btn: 'Remove',
    students_ok: 'OK',
    parent_welcome_back: 'Welcome back,',
    parent_child_registered_one: 'child registered',
    parent_children_registered: 'children registered',
    parent_my_children: 'My Children',
    parent_failed_load: 'Failed to load children',
    parent_no_children: 'No children assigned yet',
    parent_contact_teacher: 'Please contact your teacher',
    parent_points: 'Points',
    parent_completed: 'Completed',
    parent_graded: 'Graded',
    parent_detail_back: 'Back',
    parent_detail_total_points: 'Total Points',
    parent_detail_rank: 'Rank',
    parent_detail_completion: 'Completion',
    parent_detail_overview: 'Overview',
    parent_detail_homeworks: 'Homeworks',
    parent_detail_ranking: 'Ranking',
    parent_detail_progress_overview: 'Progress Overview',
    parent_detail_homework_completion: 'Homework Completion',
    parent_detail_total_homeworks: 'Total Homeworks',
    parent_detail_no_homeworks: 'No homeworks found',
    parent_detail_teacher_comment: 'Teacher comment:',
    parent_detail_all: 'All',
    parent_detail_current_position: 'Current Position',
    parent_detail_out_of_students: 'out of {n} students',
    parent_detail_top_5: 'Top 5 Students',
    parent_detail_your_child: '(Your child)',
    parent_detail_graded: 'graded',
    parent_detail_points: 'points',
    parent_detail_ranked: 'Your child is currently ranked #{n}',
    parent_detail_not_top_5: 'Unfortunately, your child is not in the top 5 yet. Encourage them to complete more homework and earn better grades to climb up the rankings!',
    loader_loading: 'Loading...',
    ranking_no_group: 'You are not assigned to any group yet',
    ranking_contact_teacher: 'Please contact your teacher to be assigned to a group',
    ranking_retry: 'Retry',
    ranking_no_data: 'No ranking data available',
    ranking_weekly: 'Weekly',
    ranking_monthly: 'Monthly',
    ranking_yearly: 'Yearly',
    ranking_place: 'Place',
    ranking_top_percent: 'Top {percent}% of your class',
    ranking_points: 'Points',
    ranking_top_students: 'Top Students',
    ranking_you: '(You)',
    ranking_monthly_reward: 'Monthly Reward',
    ranking_win_prize: 'Be #1 to win this prize!',
    ranking_remaining: 'remaining',
    ranking_click_full: 'Click to view full size',
    ranking_finish_top: 'Finish this month as the top student to win!',
    ranking_ended: 'Ended',
    ranking_status_perfect: 'Perfect',
    ranking_status_better: 'Better',
    ranking_status_good: 'Good',
    ranking_status_bad: 'Bad',
    ranking_status_worse: 'Worse',
    ranking_error_fetch: 'Failed to fetch ranking data',
    settings_language: 'Language',
    settings_account: 'Account',
    settings_username: 'Username',
    settings_change_password: 'Change Password',
    settings_center: 'Center',
    settings_current_plan: 'Current plan',
    settings_center_logo: 'Center logo',
    settings_logo_placeholder: 'Image URL (e.g. https://...)',
    settings_save: 'Save',
    settings_preferences: 'Preferences',
    settings_dark_mode: 'Dark Mode',
    settings_support_teachers: 'Assistant Teachers',
    settings_add: 'Add',
    settings_no_support_teachers: 'No assistant teachers',
    settings_support: 'Support',
    settings_telegram: 'Telegram',
    settings_log_out: 'Log Out',
    settings_version: 'Version',
    settings_current_password: 'Current Password',
    settings_enter_current_password: 'Enter current password',
    settings_new_password: 'New Password',
    settings_enter_new_password: 'Enter new password',
    settings_cancel: 'Cancel',
    settings_change: 'Change',
    settings_change_profile_image: 'Change Profile Image',
    settings_uploading: 'Uploading...',
    settings_upload: 'Upload',
    settings_edit_support_teacher: 'Edit Assistant Teacher',
    settings_new_support_teacher: 'New Assistant Teacher',
    settings_full_name: 'Full Name *',
    settings_enter_full_name: 'Enter full name',
    settings_login: 'Login *',
    settings_enter_username: 'Enter username',
    settings_password: 'Password',
    settings_password_optional: '(leave blank to keep unchanged)',
    settings_new_password_optional: 'New password (optional)',
    settings_phone: 'Phone',
    settings_groups: 'Groups',
    settings_all_groups: 'All Groups',
    settings_no_groups: 'No groups available',
    settings_create: 'Create',
    settings_error_name_login_required: 'Full name and login are required',
    settings_error_password_required: 'Password is required',
    settings_error_generic: 'An error occurred',
    settings_confirm_delete: 'Are you sure you want to delete?',
    settings_error_file_size: 'File size must be less than 5MB',
    settings_error_no_file: 'No file selected',
    settings_error_upload_failed: 'Upload failed',
    settings_error_password_failed: 'Failed to change password',
    settings_math_teacher: 'Mathematics Teacher',
    appointment_title: 'Additional classes',
    appointment_subtitle: 'Schedule a session with assistant teachers',
    appointment_tab_book: 'Book',
    appointment_tab_my: 'My appointments',
    appointment_days_available: 'days available',
    appointment_btn_book: 'Book',
    appointment_no_teachers: 'No teachers with available slots at the moment',
    appointment_booking_disabled: 'Booking is temporarily disabled',
    appointment_blocked_title: 'You are temporarily blocked',
    appointment_blocked_message: 'You missed a booked session. You can book again in {n} days.',
    appointment_no_appointments: "You haven't booked any sessions yet",
    appointment_book_now: 'Book now',
    appointment_status_pending: 'Pending',
    appointment_status_approved: 'Approved',
    appointment_status_rejected: 'Rejected',
    appointment_status_completed: 'Completed',
    appointment_status_cancelled: 'Cancelled',
    appointment_modal_title: 'Book session',
    appointment_select_day: 'Select day',
    appointment_loading_times: 'Loading available times...',
    appointment_available_times: 'Available times:',
    appointment_start_time: 'Start time',
    appointment_no_time_today: 'No available time on this day',
    appointment_select_another_day: 'Please select another day',
    appointment_duration: 'Duration (min 30 min, max 4 hours)',
    appointment_selected_time: 'Selected time:',
    appointment_reason_label: 'What do you need help with?',
    appointment_reason_placeholder: 'e.g. Need help with Math, exam preparation...',
    appointment_confirm_btn: 'Book session',
    appointment_cancel_confirm_title: 'Cancel appointment?',
    appointment_cancel_confirm_message: 'Are you sure you want to cancel this appointment?',
    appointment_no: 'No',
    appointment_yes_cancel: 'Yes, cancel',
    appointment_notice_title: 'Important notice',
    appointment_notice_intro: 'Please note:',
    appointment_notice_blocked: "If you don't attend the booked session, you will be blocked from booking for 2 weeks.",
    appointment_notice_attend: 'Make sure you can attend before confirming.',
    appointment_notice_cancel_advance: "If you can't attend, please cancel in advance.",
    appointment_booking_loading: 'Booking...',
    appointment_understand_book: 'I understand, book',
    appointment_toast_booked: 'Appointment booked! Please wait for confirmation.',
    appointment_toast_cancelled: 'Appointment cancelled',
    appointment_rejection_reason: 'Reason:',
    appointment_unknown: 'Unknown',
    admin_assistant_teachers: 'Assistant teachers',
    admin_parents: 'Parents',
    admin_search_placeholder: 'Search...',
    admin_add_teacher: 'Add teacher',
    admin_loading: 'Loading...',
    admin_no_teachers: 'No teachers',
    admin_no_teachers_search: 'No teachers found',
    admin_groups_students: 'groups, students',
    admin_plan_plans: 'Plan options',
    admin_plan_current: 'Current',
    admin_plan_per_month: '/month',
    admin_plan_students: 'students',
    admin_plan_teachers: 'teachers',
    admin_plan_assistant: 'assistant',
    admin_plan_change: 'Change plan: @dohomework_support',
    admin_stats_error: 'Failed to load statistics',
    admin_chart_title: 'Statistics',
    admin_tasks_stats_title: 'Task statistics',
    admin_tasks_total: 'Total tasks',
    admin_tasks_new: 'New',
    admin_tasks_pending: 'Pending',
    admin_tasks_reviewed: 'Reviewed',
    admin_tasks_overdue: 'Overdue',
    admin_tasks_chart_subtitle: 'Distribution by status',
    admin_teacher_required: 'Name, login and password are required',
    admin_password_min: 'Password must be at least 8 characters',
    admin_teacher_added: 'Teacher added',
    admin_teacher_add_failed: 'Failed to add teacher',
    admin_refresh: 'Refresh',
    admin_new_teacher: 'New teacher',
    admin_full_name: 'Full name *',
    admin_full_name_placeholder: 'Full name',
    admin_phone: 'Phone',
    admin_phone_placeholder: '90 123 45 67',
    admin_password_hint: 'At least 8 characters',
    admin_subject: 'Subject / field',
    admin_subject_placeholder: 'e.g. Mathematics',
    admin_teacher_groups_rating: 'Groups and rating',
    admin_teacher_student_count: 'students',
    admin_teacher_click_ranking: 'Click a group to see student ranking',
    admin_teacher_no_groups: 'No groups',
    admin_teacher_data_error: 'Failed to load data',
    admin_students_count_word: 'students',
    admin_students_search_placeholder: 'Search by name, login, phone, group...',
    admin_students_load_error: 'Failed to load students',
    admin_students_not_found: 'No students found',
    admin_students_empty: 'Student list is empty',
    admin_students_search_other: 'Try another search term',
    admin_students_add_via_teachers: 'Students are added by teachers',
    admin_teacher_label: 'Teacher:',
  },
  ru: {
    nav_dashboard: 'Панель',
    nav_students: 'Ученики',
    nav_settings: 'Настройки',
    nav_groups: 'Группы',
    nav_schedule: 'Расписание',
    nav_students_teacher: 'Ученики',
    nav_tasks: 'Задания',
    nav_profile: 'Профиль',
    nav_organizations: 'Организации',
    nav_admins: 'Админы',
    nav_teachers: 'Учителя',
    nav_teacher_detail: 'Учитель',
    nav_notifications: 'Уведомления',
    nav_grading: 'Оценки',
    nav_student: 'Ученик',
    nav_parent: 'Родитель',
    nav_support: 'Поддержка',
    logout: 'Выход',
    center_admin: 'Админ центра',
    teacher: 'Учитель',
    superadmin: 'Суперадмин',
    student_my_homeworks: 'Мои задания',
    student_greeting_morning: 'Доброе утро',
    student_greeting_afternoon: 'Добрый день',
    student_greeting_evening: 'Добрый вечер',
    student_fallback: 'Ученик',
    student_pending: 'В ожидании',
    student_submitted: 'Отправлено',
    student_graded: 'Проверено',
    student_overdue: 'Просрочено',
    student_all: 'Все',
    student_book_appointment: 'Дополнительные занятия',
    student_with_support_teacher: 'С помощником учителя',
    student_no_homework: 'Заданий нет',
    student_teacher_fallback: 'Учитель',
    student_submitted_on: 'Отправлено',
    student_retry: 'Повторить',
    nav_home: 'Главная',
    nav_ranking: 'Рейтинг',
    nav_appointments: 'Записи',
    schedule_my_schedule: 'Моё расписание',
    schedule_teacher: 'Учитель:',
    schedule_not_assigned: 'Не назначен',
    schedule_today: 'Сегодня',
    schedule_class: 'урок',
    schedule_classes: 'уроков',
    schedule_practice_count: 'практика',
    schedule_no_classes: 'Нет занятий',
    schedule_free_day: 'Выходной! 🎉',
    schedule_now: 'Сейчас',
    schedule_soon: 'Скоро',
    schedule_done: 'Завершено',
    schedule_in_progress: 'Идёт',
    schedule_min_left: 'мин осталось',
    schedule_practice: 'Практика',
    schedule_week_overview: 'Неделя',
    schedule_retry: 'Повторить',
    schedule_contact_teacher: 'Свяжитесь с учителем',
    schedule_mon: 'Пн', schedule_tue: 'Вт', schedule_wed: 'Ср', schedule_thu: 'Чт', schedule_fri: 'Пт', schedule_sat: 'Сб', schedule_sun: 'Вс',
    schedule_monday: 'Понедельник', schedule_tuesday: 'Вторник', schedule_wednesday: 'Среда', schedule_thursday: 'Четверг', schedule_friday: 'Пятница', schedule_saturday: 'Суббота', schedule_sunday: 'Воскресенье',
    schedule_groups: 'групп',
    schedule_add_practice_lesson: '+ Добавить практику',
    schedule_add_practice_modal_title: 'Добавить практическое занятие',
    schedule_add_practice_modal_subtitle: 'Запланировать дополнительный урок',
    schedule_group_label: 'Группа',
    schedule_select_group: 'Выберите группу',
    schedule_all_groups: 'Все группы',
    schedule_date: 'Дата',
    schedule_start_time: 'Начало',
    schedule_end_time: 'Конец',
    schedule_description_optional: 'Описание (необяз.)',
    schedule_description_placeholder: 'напр., Подготовка к экзамену',
    schedule_saving: 'Сохранение...',
    schedule_add_practice_btn: 'Добавить',
    schedule_fetch_error: 'Не удалось загрузить расписание',
    students_my_students: 'Мои ученики',
    students_count: 'учеников',
    students_count_parents: 'родителей',
    students_tab_students: 'Ученики',
    students_tab_parents: 'Родители',
    students_search_students: 'Поиск по имени, телефону или группе...',
    students_search_parents: 'Поиск по имени или телефону...',
    students_no_students: 'Ученики не найдены',
    students_no_parents: 'Родители не найдены',
    students_children: 'Дети:',
    students_call: 'Позвонить',
    students_remove_parent: 'Удалить родителя',
    students_assign_parent: 'Назначить родителя',
    students_add_student: 'Добавить ученика',
    students_add_parent: 'Добавить родителя',
    students_modal_new_student: 'Новый ученик',
    students_modal_fio: 'Ф.И.О *',
    students_modal_fio_placeholder: 'Ф.И.О ученика',
    students_modal_phone: 'Телефон *',
    students_modal_login: 'Логин *',
    students_modal_password: 'Пароль *',
    students_modal_assign_group: 'Прикрепить к группе',
    students_modal_select_group: 'Выберите группу',
    students_modal_loading: 'Загрузка...',
    students_modal_add_student_btn: 'Добавить ученика',
    students_modal_create_parent_title: 'Создать родителя',
    students_modal_full_name: 'Ф.И.О *',
    students_modal_parent_name_placeholder: 'Ф.И.О родителя',
    students_modal_creating: 'Создание...',
    students_modal_create_parent_btn: 'Создать родителя',
    students_modal_assign_children: 'Прикрепить детей (необяз.)',
    students_modal_no_group: 'Без группы',
    students_modal_assign_parent_title: 'Назначить родителя',
    students_modal_assign_to: 'Назначить родителя для',
    students_modal_no_parents_yet: 'Родители ещё не созданы',
    students_modal_create_parent_first: 'Сначала создайте родителя',
    students_modal_select_parent: 'Выберите родителя',
    students_modal_select_parent_placeholder: 'Выберите родителя...',
    students_modal_assigning: 'Назначение...',
    students_modal_assign_btn: 'Назначить',
    students_modal_new: 'Новый',
    students_modal_edit_parent: 'Редактировать родителя',
    students_modal_new_password: 'Новый пароль',
    students_modal_password_leave_empty: 'Оставьте пустым, чтобы не менять',
    students_modal_password_leave_empty_hint: 'Оставьте пустым, если не хотите менять пароль',
    students_modal_assigned_children: 'Прикреплённые дети',
    students_modal_saving: 'Сохранение...',
    students_modal_save_changes: 'Сохранить',
    students_confirm_delete_parent: 'Удалить родителя',
    students_confirm_remove_parent: 'Отвязать родителя',
    students_confirm_delete_message: 'Вы уверены, что хотите удалить {name}? Родитель будет отвязан от всех учеников.',
    students_confirm_remove_message: 'Вы уверены, что хотите отвязать родителя от {name}?',
    students_confirm_delete_btn: 'Удалить',
    students_confirm_remove_btn: 'Отвязать',
    students_ok: 'OK',
    parent_welcome_back: 'С возвращением,',
    parent_child_registered_one: 'ребёнок зарегистрирован',
    parent_children_registered: 'детей зарегистрировано',
    parent_my_children: 'Мои дети',
    parent_failed_load: 'Не удалось загрузить данные',
    parent_no_children: 'Дети пока не прикреплены',
    parent_contact_teacher: 'Обратитесь к учителю',
    parent_points: 'Баллы',
    parent_completed: 'Выполнено',
    parent_graded: 'Проверено',
    parent_detail_back: 'Назад',
    parent_detail_total_points: 'Всего баллов',
    parent_detail_rank: 'Место',
    parent_detail_completion: 'Выполнение',
    parent_detail_overview: 'Обзор',
    parent_detail_homeworks: 'Домашние задания',
    parent_detail_ranking: 'Рейтинг',
    parent_detail_progress_overview: 'Обзор прогресса',
    parent_detail_homework_completion: 'Выполнение ДЗ',
    parent_detail_total_homeworks: 'Всего заданий',
    parent_detail_no_homeworks: 'Заданий не найдено',
    parent_detail_teacher_comment: 'Комментарий учителя:',
    parent_detail_all: 'Все',
    parent_detail_current_position: 'Текущее место',
    parent_detail_out_of_students: 'из {n} учеников',
    parent_detail_top_5: 'Топ-5 учеников',
    parent_detail_your_child: '(Ваш ребёнок)',
    parent_detail_graded: 'проверено',
    parent_detail_points: 'баллов',
    parent_detail_ranked: 'Ваш ребёнок на #{n} месте',
    parent_detail_not_top_5: 'Пока ваш ребёнок не в топ-5. Поддержите его — пусть выполняет больше заданий и улучшает оценки, чтобы подняться в рейтинге!',
    loader_loading: 'Загрузка...',
    ranking_no_group: 'Вы пока не прикреплены ни к одной группе',
    ranking_contact_teacher: 'Обратитесь к учителю для записи в группу',
    ranking_retry: 'Повторить',
    ranking_no_data: 'Нет данных рейтинга',
    ranking_weekly: 'Неделя',
    ranking_monthly: 'Месяц',
    ranking_yearly: 'Год',
    ranking_place: 'место',
    ranking_top_percent: 'Топ {percent}% в классе',
    ranking_points: 'баллов',
    ranking_top_students: 'Лучшие ученики',
    ranking_you: '(Вы)',
    ranking_monthly_reward: 'Награда месяца',
    ranking_win_prize: 'Стань первым и забери приз!',
    ranking_remaining: 'осталось',
    ranking_click_full: 'Нажмите для полного размера',
    ranking_finish_top: 'Заверши месяц первым и победи!',
    ranking_ended: 'Завершено',
    ranking_status_perfect: 'Отлично',
    ranking_status_better: 'Хорошо',
    ranking_status_good: 'Нормально',
    ranking_status_bad: 'Плохо',
    ranking_status_worse: 'Очень плохо',
    ranking_error_fetch: 'Не удалось загрузить рейтинг',
    settings_language: 'Язык',
    settings_account: 'Аккаунт',
    settings_username: 'Имя пользователя',
    settings_change_password: 'Изменить пароль',
    settings_center: 'Центр',
    settings_current_plan: 'Текущий тариф',
    settings_center_logo: 'Логотип центра',
    settings_logo_placeholder: 'URL изображения (напр. https://...)',
    settings_save: 'Сохранить',
    settings_preferences: 'Настройки',
    settings_dark_mode: 'Тёмная тема',
    settings_support_teachers: 'Помощники учителя',
    settings_add: 'Добавить',
    settings_no_support_teachers: 'Нет помощников',
    settings_support: 'Поддержка',
    settings_telegram: 'Telegram',
    settings_log_out: 'Выйти',
    settings_version: 'Версия',
    settings_current_password: 'Текущий пароль',
    settings_enter_current_password: 'Введите текущий пароль',
    settings_new_password: 'Новый пароль',
    settings_enter_new_password: 'Введите новый пароль',
    settings_cancel: 'Отмена',
    settings_change: 'Изменить',
    settings_change_profile_image: 'Изменить фото',
    settings_uploading: 'Загрузка...',
    settings_upload: 'Загрузить',
    settings_edit_support_teacher: 'Редактировать помощника',
    settings_new_support_teacher: 'Новый помощник',
    settings_full_name: 'ФИО *',
    settings_enter_full_name: 'Введите ФИО',
    settings_login: 'Логин *',
    settings_enter_username: 'Введите логин',
    settings_password: 'Пароль',
    settings_password_optional: '(оставьте пустым, чтобы не менять)',
    settings_new_password_optional: 'Новый пароль (необяз.)',
    settings_phone: 'Телефон',
    settings_groups: 'Группы',
    settings_all_groups: 'Все группы',
    settings_no_groups: 'Нет доступных групп',
    settings_create: 'Создать',
    settings_error_name_login_required: 'ФИО и логин обязательны',
    settings_error_password_required: 'Пароль обязателен',
    settings_error_generic: 'Произошла ошибка',
    settings_confirm_delete: 'Вы уверены, что хотите удалить?',
    settings_error_file_size: 'Размер файла не более 5 МБ',
    settings_error_no_file: 'Файл не выбран',
    settings_error_upload_failed: 'Ошибка загрузки',
    settings_error_password_failed: 'Не удалось изменить пароль',
    settings_math_teacher: 'Учитель математики',
    appointment_title: 'Дополнительные занятия',
    appointment_subtitle: 'Запишитесь на занятие с помощником учителя',
    appointment_tab_book: 'Запись',
    appointment_tab_my: 'Мои записи',
    appointment_days_available: 'дней доступно',
    appointment_btn_book: 'Записаться',
    appointment_no_teachers: 'Нет учителей со свободными слотами',
    appointment_booking_disabled: 'Запись временно отключена',
    appointment_blocked_title: 'Вы временно заблокированы',
    appointment_blocked_message: 'Вы пропустили занятие. Запись снова доступна через {n} дн.',
    appointment_no_appointments: 'У вас пока нет записей',
    appointment_book_now: 'Записаться',
    appointment_status_pending: 'Ожидание',
    appointment_status_approved: 'Подтверждено',
    appointment_status_rejected: 'Отклонено',
    appointment_status_completed: 'Проведено',
    appointment_status_cancelled: 'Отменено',
    appointment_modal_title: 'Запись на занятие',
    appointment_select_day: 'Выберите день',
    appointment_loading_times: 'Загрузка времени...',
    appointment_available_times: 'Доступное время:',
    appointment_start_time: 'Время начала',
    appointment_no_time_today: 'Нет времени в этот день',
    appointment_select_another_day: 'Выберите другой день',
    appointment_duration: 'Длительность (от 30 мин до 4 ч)',
    appointment_selected_time: 'Выбрано:',
    appointment_reason_label: 'С чем нужна помощь?',
    appointment_reason_placeholder: 'Напр. математика, подготовка к экзамену...',
    appointment_confirm_btn: 'Записаться',
    appointment_cancel_confirm_title: 'Отменить запись?',
    appointment_cancel_confirm_message: 'Вы уверены, что хотите отменить запись?',
    appointment_no: 'Нет',
    appointment_yes_cancel: 'Да, отменить',
    appointment_notice_title: 'Важно',
    appointment_notice_intro: 'Обратите внимание:',
    appointment_notice_blocked: 'При неявке вы будете заблокированы на 2 недели.',
    appointment_notice_attend: 'Убедитесь, что сможете прийти.',
    appointment_notice_cancel_advance: 'Если не сможете прийти — отмените заранее.',
    appointment_booking_loading: 'Запись...',
    appointment_understand_book: 'Понятно, записаться',
    appointment_toast_booked: 'Запись создана! Ожидайте подтверждения.',
    appointment_toast_cancelled: 'Запись отменена',
    appointment_rejection_reason: 'Причина:',
    appointment_unknown: 'Неизвестно',
    admin_assistant_teachers: 'Помощники учителя',
    admin_parents: 'Родители',
    admin_search_placeholder: 'Поиск...',
    admin_add_teacher: 'Добавить учителя',
    admin_loading: 'Загрузка...',
    admin_no_teachers: 'Нет учителей',
    admin_no_teachers_search: 'Учителя не найдены',
    admin_groups_students: 'групп, учеников',
    admin_plan_plans: 'Тарифные планы',
    admin_plan_current: 'Текущий',
    admin_plan_per_month: '/мес',
    admin_plan_students: 'учеников',
    admin_plan_teachers: 'учителей',
    admin_plan_assistant: 'помощников',
    admin_plan_change: 'Изменить тариф: @dohomework_support',
    admin_stats_error: 'Не удалось загрузить статистику',
    admin_chart_title: 'Статистика',
    admin_tasks_stats_title: 'Статистика по заданиям',
    admin_tasks_total: 'Всего заданий',
    admin_tasks_new: 'Новые',
    admin_tasks_pending: 'На проверке',
    admin_tasks_reviewed: 'Проверены',
    admin_tasks_overdue: 'Просрочены',
    admin_tasks_chart_subtitle: 'Распределение по статусам',
    admin_teacher_required: 'Укажите ФИО, логин и пароль',
    admin_password_min: 'Пароль не менее 8 символов',
    admin_teacher_added: 'Учитель добавлен',
    admin_teacher_add_failed: 'Не удалось добавить учителя',
    admin_refresh: 'Обновить',
    admin_new_teacher: 'Новый учитель',
    admin_full_name: 'ФИО *',
    admin_full_name_placeholder: 'Полное имя',
    admin_phone: 'Телефон',
    admin_phone_placeholder: '90 123 45 67',
    admin_password_hint: 'Не менее 8 символов',
    admin_subject: 'Предмет / направление',
    admin_subject_placeholder: 'Напр. Математика',
    admin_teacher_groups_rating: 'Группы и рейтинг',
    admin_teacher_student_count: 'учеников',
    admin_teacher_click_ranking: 'Нажмите на группу, чтобы увидеть рейтинг учеников',
    admin_teacher_no_groups: 'Нет групп',
    admin_teacher_data_error: 'Не удалось загрузить данные',
    admin_students_count_word: 'учеников',
    admin_students_search_placeholder: 'Поиск по имени, логину, телефону, группе...',
    admin_students_load_error: 'Не удалось загрузить учеников',
    admin_students_not_found: 'Ученики не найдены',
    admin_students_empty: 'Список учеников пуст',
    admin_students_search_other: 'Попробуйте другие слова',
    admin_students_add_via_teachers: 'Учеников добавляют учителя',
    admin_teacher_label: 'Учитель:',
  },
  uz: {
    nav_dashboard: 'Panel',
    nav_students: "O'quvchilar",
    nav_settings: 'Sozlamalar',
    nav_groups: 'Guruhlar',
    nav_schedule: 'Jadval',
    nav_students_teacher: "O'quvchilar",
    nav_tasks: 'Vazifalar',
    nav_profile: 'Profil',
    nav_organizations: 'Tashkilotlar',
    nav_admins: 'Adminlar',
    nav_teachers: "O'qituvchilar",
    nav_teacher_detail: "O'qituvchi",
    nav_notifications: 'Bildirishnomalar',
    nav_grading: 'Baholash',
    nav_student: "O'quvchi",
    nav_parent: 'Ota-ona',
    nav_support: 'Qo\'llab-quvvatlash',
    logout: 'Chiqish',
    center_admin: 'Markaz admin',
    teacher: "O'qituvchi",
    superadmin: 'Superadmin',
    student_my_homeworks: "Vazifalarim",
    student_greeting_morning: 'Xayrli tong',
    student_greeting_afternoon: 'Xayrli kun',
    student_greeting_evening: 'Xayrli kech',
    student_fallback: "O'quvchi",
    student_pending: 'Kutilmoqda',
    student_submitted: 'Yuborilgan',
    student_graded: 'Baholangan',
    student_overdue: 'Muddati o\'tgan',
    student_all: 'Barchasi',
    student_book_appointment: "Qo'shimcha darsga o'tish",
    student_with_support_teacher: "Yordamchi o'qituvchi bilan shug'ullanish",
    student_no_homework: 'Vazifa topilmadi',
    student_teacher_fallback: "O'qituvchi",
    student_submitted_on: 'Yuborilgan',
    student_retry: 'Qayta urinish',
    nav_home: 'Bosh sahifa',
    nav_ranking: 'Reyting',
    nav_appointments: 'Uchrashuvlar',
    schedule_my_schedule: 'Jadvalim',
    schedule_teacher: "O'qituvchi:",
    schedule_not_assigned: "Tayinlanmagan",
    schedule_today: 'Bugun',
    schedule_class: 'dars',
    schedule_classes: 'dars',
    schedule_practice_count: 'amaliyot',
    schedule_no_classes: 'Darslar yo\'q',
    schedule_free_day: 'Dam oling! 🎉',
    schedule_now: 'Hozir',
    schedule_soon: 'Tez kunda',
    schedule_done: 'Tugadi',
    schedule_in_progress: 'Davom etmoqda',
    schedule_min_left: 'daq qoldi',
    schedule_practice: 'Amaliyot',
    schedule_week_overview: 'Hafta',
    schedule_retry: 'Qayta urinish',
    schedule_contact_teacher: "O'qituvchingiz bilan bog'laning",
    schedule_mon: 'Du', schedule_tue: 'Se', schedule_wed: 'Ch', schedule_thu: 'Pa', schedule_fri: 'Ju', schedule_sat: 'Sh', schedule_sun: 'Ya',
    schedule_monday: 'Dushanba', schedule_tuesday: 'Seshanba', schedule_wednesday: 'Chorshanba', schedule_thursday: 'Payshanba', schedule_friday: 'Juma', schedule_saturday: 'Shanba', schedule_sunday: 'Yakshanba',
    schedule_groups: 'guruh',
    schedule_add_practice_lesson: '+ Amaliyot qo\'shish',
    schedule_add_practice_modal_title: 'Amaliyot darsi qo\'shish',
    schedule_add_practice_modal_subtitle: 'Qo\'shimcha dars rejalashtiring',
    schedule_group_label: 'Guruh',
    schedule_select_group: 'Guruhni tanlang',
    schedule_all_groups: 'Barcha guruhlar',
    schedule_date: 'Sana',
    schedule_start_time: 'Boshlanish',
    schedule_end_time: 'Tugash',
    schedule_description_optional: 'Tavsif (ixtiyoriy)',
    schedule_description_placeholder: 'masalan, Imtihonga tayyorgarlik',
    schedule_saving: 'Saqlanmoqda...',
    schedule_add_practice_btn: 'Amaliyot qo\'shish',
    schedule_fetch_error: 'Jadval yuklanmadi',
    students_my_students: "O'quvchilarim",
    students_count: "o'quvchi",
    students_count_parents: 'ota-ona',
    students_tab_students: "O'quvchilar",
    students_tab_parents: 'Ota-onalar',
    students_search_students: "Ism, telefon yoki guruh bo'yicha qidirish...",
    students_search_parents: "Ism yoki telefon bo'yicha qidirish...",
    students_no_students: "O'quvchilar topilmadi",
    students_no_parents: 'Ota-onalar topilmadi',
    students_children: "Farzandlar:",
    students_call: "Qo'ng'iroq",
    students_remove_parent: "Ota-onani olib tashlash",
    students_assign_parent: "Ota-onani biriktirish",
    students_add_student: "O'quvchi qo'shish",
    students_add_parent: "Ota-ona qo'shish",
    students_modal_new_student: "Yangi o'quvchi",
    students_modal_fio: 'F.I.O *',
    students_modal_fio_placeholder: "O'quvchi F.I.O",
    students_modal_phone: 'Telefon *',
    students_modal_login: 'Login *',
    students_modal_password: 'Parol *',
    students_modal_assign_group: "Guruhga biriktirish",
    students_modal_select_group: 'Guruhni tanlang',
    students_modal_loading: 'Yuklanmoqda...',
    students_modal_add_student_btn: "O'quvchi qo'shish",
    students_modal_create_parent_title: 'Ota-ona qo\'shish',
    students_modal_full_name: 'F.I.O *',
    students_modal_parent_name_placeholder: 'Ota-ona F.I.O',
    students_modal_creating: 'Yuklanmoqda...',
    students_modal_create_parent_btn: 'Ota-ona qo\'shish',
    students_modal_assign_children: "Farzandlarni biriktirish (ixtiyoriy)",
    students_modal_no_group: "Guruhsiz",
    students_modal_assign_parent_title: "Ota-onani biriktirish",
    students_modal_assign_to: "Biriktirish",
    students_modal_no_parents_yet: "Ota-onalar hali yaratilmagan",
    students_modal_create_parent_first: "Avval ota-ona qo'shing",
    students_modal_select_parent: "Ota-onani tanlang",
    students_modal_select_parent_placeholder: "Ota-onani tanlang...",
    students_modal_assigning: "Biriktirilmoqda...",
    students_modal_assign_btn: "Ota-onani biriktirish",
    students_modal_new: "Yangi",
    students_modal_edit_parent: "Ota-onani tahrirlash",
    students_modal_new_password: 'Yangi parol',
    students_modal_password_leave_empty: "O'zgartirmaslik uchun bo'sh qoldiring",
    students_modal_password_leave_empty_hint: "Parolni o'zgartirmaslik uchun bo'sh qoldiring",
    students_modal_assigned_children: "Biriktirilgan farzandlar",
    students_modal_saving: 'Saqlanmoqda...',
    students_modal_save_changes: "O'zgarishlarni saqlash",
    students_confirm_delete_parent: "Ota-onani o'chirish",
    students_confirm_remove_parent: "Ota-onani olib tashlash",
    students_confirm_delete_message: "{name} ni o'chirishni xohlaysizmi? Ota-ona barcha o'quvchilardan ham olib tashlanadi.",
    students_confirm_remove_message: "{name} dan ota-onani olib tashlashni xohlaysizmi?",
    students_confirm_delete_btn: "O'chirish",
    students_confirm_remove_btn: "Olib tashlash",
    students_ok: 'OK',
    parent_welcome_back: 'Xush kelibsiz,',
    parent_child_registered_one: "farzand ro'yxatdan o'tgan",
    parent_children_registered: "farzand ro'yxatdan o'tgan",
    parent_my_children: "Farzandlarim",
    parent_failed_load: "Ma'lumotlar yuklanmadi",
    parent_no_children: "Farzandlar hali biriktirilmagan",
    parent_contact_teacher: "O'qituvchingiz bilan bog'laning",
    parent_points: 'Ball',
    parent_completed: 'Bajarildi',
    parent_graded: 'Baholangan',
    parent_detail_back: 'Orqaga',
    parent_detail_total_points: "Jami ball",
    parent_detail_rank: 'O\'rin',
    parent_detail_completion: 'Bajarilishi',
    parent_detail_overview: 'Umumiy',
    parent_detail_homeworks: 'Vazifalar',
    parent_detail_ranking: 'Reyting',
    parent_detail_progress_overview: 'Progress',
    parent_detail_homework_completion: 'Vazifalar bajarilishi',
    parent_detail_total_homeworks: "Jami vazifalar",
    parent_detail_no_homeworks: "Vazifalar topilmadi",
    parent_detail_teacher_comment: "O'qituvchi izohi:",
    parent_detail_all: "Hammasi",
    parent_detail_current_position: "Joriy o'rin",
    parent_detail_out_of_students: "{n} ta o'quvchidan",
    parent_detail_top_5: "Eng yaxshi 5 o'quvchi",
    parent_detail_your_child: '(Sizning farzandingiz)',
    parent_detail_graded: 'baholangan',
    parent_detail_points: 'ball',
    parent_detail_ranked: "Farzandingiz hozir #{n} o'rinda",
    parent_detail_not_top_5: "Hozircha farzandingiz eng yaxshi 5 talikda emas. Ko'proq vazifa bajarish va yaxshi baholar olishga undang!",
    loader_loading: 'Yuklanmoqda...',
    ranking_no_group: "Siz hali hech qanday guruhga biriktirilmagansiz",
    ranking_contact_teacher: "Guruhga biriktirilish uchun o'qituvchingiz bilan bog'laning",
    ranking_retry: 'Qayta urinish',
    ranking_no_data: 'Reyting ma\'lumoti yo\'q',
    ranking_weekly: 'Haftalik',
    ranking_monthly: 'Oylik',
    ranking_yearly: 'Yillik',
    ranking_place: 'o\'rin',
    ranking_top_percent: 'Sinfdagi eng yaxshi {percent}%',
    ranking_points: 'ball',
    ranking_top_students: 'Eng yaxshi o\'quvchilar',
    ranking_you: '(Siz)',
    ranking_monthly_reward: 'Oy sovg\'asi',
    ranking_win_prize: '1-o\'rinni egallang va sovrinni yuting!',
    ranking_remaining: 'qoldi',
    ranking_click_full: 'To\'liq ko\'rish uchun bosing',
    ranking_finish_top: 'Oyni birinchi o\'rinda yakunlang va yuting!',
    ranking_ended: 'Tugadi',
    ranking_status_perfect: 'A\'lo',
    ranking_status_better: 'Yaxshi',
    ranking_status_good: 'Qoniqarli',
    ranking_status_bad: 'Qoniqarsiz',
    ranking_status_worse: 'Yomon',
    ranking_error_fetch: 'Reyting yuklanmadi',
    settings_language: 'Til',
    settings_account: 'Hisob',
    settings_username: 'Foydalanuvchi nomi',
    settings_change_password: 'Parolni o\'zgartirish',
    settings_center: 'Markaz',
    settings_current_plan: 'Joriy tarif',
    settings_center_logo: 'Markaz logosi',
    settings_logo_placeholder: 'Rasm URL (masalan: https://...)',
    settings_save: 'Saqlash',
    settings_preferences: 'Sozlamalar',
    settings_dark_mode: 'Qorong\'u rejim',
    settings_support_teachers: 'Yordamchi o\'qituvchilar',
    settings_add: 'Qo\'shish',
    settings_no_support_teachers: 'Yordamchi o\'qituvchilar yo\'q',
    settings_support: 'Qo\'llab-quvvatlash',
    settings_telegram: 'Telegram',
    settings_log_out: 'Chiqish',
    settings_version: 'Versiya',
    settings_current_password: 'Joriy parol',
    settings_enter_current_password: 'Joriy parolni kiriting',
    settings_new_password: 'Yangi parol',
    settings_enter_new_password: 'Yangi parolni kiriting',
    settings_cancel: 'Bekor qilish',
    settings_change: 'O\'zgartirish',
    settings_change_profile_image: 'Profil rasmini o\'zgartirish',
    settings_uploading: 'Yuklanmoqda...',
    settings_upload: 'Yuklash',
    settings_edit_support_teacher: 'Yordamchi o\'qituvchini tahrirlash',
    settings_new_support_teacher: 'Yangi yordamchi o\'qituvchi',
    settings_full_name: 'To\'liq ism *',
    settings_enter_full_name: 'To\'liq ismni kiriting',
    settings_login: 'Login *',
    settings_enter_username: 'Loginni kiriting',
    settings_password: 'Parol',
    settings_password_optional: '(o\'zgartirmaslik uchun bo\'sh qoldiring)',
    settings_new_password_optional: 'Yangi parol (ixtiyoriy)',
    settings_phone: 'Telefon',
    settings_groups: 'Guruhlar',
    settings_all_groups: 'Barcha guruhlar',
    settings_no_groups: 'Guruhlar mavjud emas',
    settings_create: 'Yaratish',
    settings_error_name_login_required: 'F.I.O va login majburiy',
    settings_error_password_required: 'Parol majburiy',
    settings_error_generic: 'Xatolik yuz berdi',
    settings_confirm_delete: 'Haqiqatan ham o\'chirmoqchimisiz?',
    settings_error_file_size: 'Fayl hajmi 5MB dan kam bo\'lishi kerak',
    settings_error_no_file: 'Fayl tanlanmagan',
    settings_error_upload_failed: 'Yuklash muvaffaqiyatsiz',
    settings_error_password_failed: 'Parol o\'zgartirish muvaffaqiyatsiz',
    settings_math_teacher: 'Matematika o\'qituvchisi',
    appointment_title: 'Qo\'shimcha darslar',
    appointment_subtitle: 'Yordamchi o\'qituvchi bilan darsga yozilish',
    appointment_tab_book: 'Yozilish',
    appointment_tab_my: 'Mening darslarim',
    appointment_days_available: 'kun mavjud',
    appointment_btn_book: 'Yozilish',
    appointment_no_teachers: 'Hozircha bo\'sh vaqtli o\'qituvchilar yo\'q',
    appointment_booking_disabled: 'Yozilish vaqtincha o\'chirilgan',
    appointment_blocked_title: 'Siz vaqtincha bloklangansiz',
    appointment_blocked_message: 'Band qilgan darsingizga kelmadingiz. {n} kundan keyin qayta yozilishingiz mumkin.',
    appointment_no_appointments: 'Sizda hali band qilingan darslar yo\'q',
    appointment_book_now: 'Hozir yozilish',
    appointment_status_pending: 'Kutilmoqda',
    appointment_status_approved: 'Tasdiqlandi',
    appointment_status_rejected: 'Rad etildi',
    appointment_status_completed: 'O\'tilgan',
    appointment_status_cancelled: 'Bekor qilindi',
    appointment_modal_title: 'Darsga yozilish',
    appointment_select_day: 'Kunni tanlang',
    appointment_loading_times: 'Mavjud vaqtlar yuklanmoqda...',
    appointment_available_times: 'Mavjud vaqtlar:',
    appointment_start_time: 'Boshlanish vaqti',
    appointment_no_time_today: 'Bu kunda bo\'sh vaqt yo\'q',
    appointment_select_another_day: 'Boshqa kunni tanlang',
    appointment_duration: 'Davomiyligi (min 30 daq, max 4 soat)',
    appointment_selected_time: 'Tanlangan vaqt:',
    appointment_reason_label: 'Yordam qaysi mavzuda kerak?',
    appointment_reason_placeholder: 'Masalan: matematika, imtihonga tayyorgarlik...',
    appointment_confirm_btn: 'Yozilishni tasdiqlash',
    appointment_cancel_confirm_title: 'Darsni bekor qilish?',
    appointment_cancel_confirm_message: 'Ushbu darsni bekor qilishga ishonchingiz komilmi?',
    appointment_no: 'Yo\'q',
    appointment_yes_cancel: 'Ha, bekor qilish',
    appointment_notice_title: 'Muhim eslatma!',
    appointment_notice_intro: 'E\'tibor bering:',
    appointment_notice_blocked: 'Band qilgan darsingizga kelmasangiz, 2 hafta yozilishdan bloklanasiz.',
    appointment_notice_attend: 'Tasdiqlashdan oldin kelishingizga ishonch hosil qiling.',
    appointment_notice_cancel_advance: 'Kela olmasangiz, oldindan bekor qiling.',
    appointment_booking_loading: 'Yozilmoqda...',
    appointment_understand_book: 'Tushundim, yozilish',
    appointment_toast_booked: 'Darsga yozildingiz! Tasdiqlanishini kuting.',
    appointment_toast_cancelled: 'Dars bekor qilindi',
    appointment_rejection_reason: 'Sabab:',
    appointment_unknown: 'Noma\'lum',
    admin_assistant_teachers: "Yordamchi o'qituvchilar",
    admin_parents: "Ota-onalar",
    admin_search_placeholder: 'Qidirish...',
    admin_add_teacher: "O'qituvchi qo'shish",
    admin_loading: 'Yuklanmoqda...',
    admin_no_teachers: "O'qituvchilar yo'q",
    admin_no_teachers_search: "O'qituvchilar topilmadi",
    admin_groups_students: "guruh, o'quvchi",
    admin_plan_plans: 'Tarif rejalari',
    admin_plan_current: 'Joriy',
    admin_plan_per_month: '/oy',
    admin_plan_students: "o'quvchi",
    admin_plan_teachers: "o'qituvchi",
    admin_plan_assistant: 'yordamchi',
    admin_plan_change: "Tarifni o'zgartirish: @dohomework_support",
    admin_stats_error: 'Statistika yuklanmadi',
    admin_chart_title: 'Statistika',
    admin_tasks_stats_title: "Vazifalar bo'yicha statistika",
    admin_tasks_total: 'Jami vazifalar',
    admin_tasks_new: 'Yangi',
    admin_tasks_pending: "Kutilmoqda",
    admin_tasks_reviewed: "Tekshirilgan",
    admin_tasks_overdue: "Muddati o'tgan",
    admin_tasks_chart_subtitle: "Holat bo'yicha taqsimot",
    admin_teacher_required: 'Ism, login va parol kiritilishi shart',
    admin_password_min: 'Parol kamida 8 ta belgidan iborat bo\'lishi kerak',
    admin_teacher_added: "O'qituvchi qo'shildi",
    admin_teacher_add_failed: "O'qituvchi qo'shib bo'lmadi",
    admin_refresh: 'Yangilash',
    admin_new_teacher: "Yangi o'qituvchi",
    admin_full_name: 'F.I.O *',
    admin_full_name_placeholder: "To'liq ism",
    admin_phone: 'Telefon',
    admin_phone_placeholder: '90 123 45 67',
    admin_password_hint: 'Kamida 8 ta belgi',
    admin_subject: "Fan / yo'nalish",
    admin_subject_placeholder: 'Masalan: Matematika',
    admin_teacher_groups_rating: "Guruhlar va reyting",
    admin_teacher_student_count: "o'quvchi",
    admin_teacher_click_ranking: "Guruhni bosib guruhdagi o'quvchilar reytingini ko'ring",
    admin_teacher_no_groups: "Guruhlar yo'q",
    admin_teacher_data_error: "Ma'lumot yuklanmadi",
    admin_students_count_word: "o'quvchi",
    admin_students_search_placeholder: "Ism, login, telefon, guruh bo'yicha qidirish...",
    admin_students_load_error: "O'quvchilar yuklanmadi",
    admin_students_not_found: "O'quvchilar topilmadi",
    admin_students_empty: "O'quvchilar ro'yxati bo'sh",
    admin_students_search_other: "Boshqa so'z bilan qidiring",
    admin_students_add_via_teachers: "O'qituvchilar orqali o'quvchi qo'shiladi",
    admin_teacher_label: "O'qituvchi:",
  },
};

interface LanguageContextValue {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY) as LangCode | null;
      if (stored === 'eng' || stored === 'ru' || stored === 'uz') return stored;
    } catch {}
    return 'uz';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const setLang = useCallback((newLang: LangCode) => {
    setLangState(newLang);
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang][key] ?? translations.uz[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export function useTranslation() {
  const { t } = useLanguage();
  return t;
}
